### ISSUE TITLE
icetbr / Advisor fork

### ISSUE THREAD

**Issue by similarion** [icetbr/vscode-theme-minimalist#1]
Hey I wanted to submit an issue with your fork for the Advisor plugin of Hearthstone but there was no issue page. 

I downloaded 1.3.2 version of the plugin, but it still indicates that I have the 1.3.1 version.

Also I'm getting this error, and the plugin keeps turning off even when I try to turn it back on or restarted HDT. It usually happens when I'm in a match and the opponent plays their first card.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HDT.Plugins.Advisor.ExtensionMethods.GetPlayedGames(Deck thisDeck) in C:\projects\Advisor\Advisor\ExtensionMethods.cs:line 72
   at HDT.Plugins.Advisor.Advisor.<>c.<UpdateCardList>b__21_6(KeyValuePair`2 x) in C:\projects\Advisor\Advisor\Advisor.cs:line 262
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__21.MoveNext() in C:\projects\Advisor\Advisor\Advisor.cs:line 262
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by icetbr** [comment]
Hi, I'll take a look. I didn't know "issues" wasn't enabled by default. it
is now. Feel free to open this as an issue if you like, I'll take a look at
this. Thanks for the info.
